package com.gatech.astroworld.spacetrader.entity;

public enum PoliticalSystems {
    ANARCHY,
    CAPITALIST_STATE,
    COMMUNIST_STATE,
    CONFEDERACY,
    CORPORATE_STATE,
    CYBERNETIC_STATE,
    DEMOCRACY,
    DICTATORSHIP,
    FASCIST_STATE,
    FEUDAL_STATE,
    MILITARY_STATE,
    MONARCHY,
    PACIFIST_STATE,
    SOCIALIST_STATE,
    STATE_OF_SATORI,
    TECHNOCRACY,
    THEOCRACY
}
